const $=id=>document.getElementById(id);
function safeStorage(kind){try{const s=window[kind];s.getItem('x');return s}catch{return undefined}}
const session=safeStorage('sessionStorage');
const seen=SeenStore.create(safeStorage('localStorage'));
const latestList=SearchBox.latest();
const videos=VideoBlocks.create(document);
// Keyword filter: reloads page 1 keeping category and source. Clearing the box
// is not an explicit view of the category, so it does not mark it seen.
const search=SearchBox.create((q,{explicit})=>{page=1;loadArticles({userAction:explicit}).catch(error)});
let token=(session&&session.getItem('news-token'))||'',authRequired=true,page=1,sources=[],categories=[],category='',view='news';
const fmt=s=>s?new Date(s).toLocaleString('vi-VN'):'Chưa cập nhật';
const statusText={full:'Toàn văn',summary:'Tóm tắt · đang chờ lấy nội dung',unavailable:'Chỉ có tóm tắt'};
const catName=slug=>(categories.find(c=>c.slug===slug)||{}).name||slug;
function node(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n}
// A small red dot marks new articles; the count is not shown. The text is for
// screen readers only.
function newDot(label){const d=node('span',undefined,'new-dot');d.append(node('span',' '+label,'sr-only'));return d}
// Source name with the site's icon, stored locally in web/icons (one per
// adapter). Unknown adapter or a failed load shows an abbreviation instead.
const siteIcons={vnexpress:['/icons/vnexpress.png','VN'],bbc:['/icons/bbc.png','BBC'],tuoitre:['/icons/tuoitre.png','TT']};
function sourceLabel(adapter,name,cls){const wrap=node('span',undefined,'src'+(cls?' '+cls:''));const [icon,abbr]=siteIcons[adapter]||['',(name||'?').slice(0,2).toUpperCase()];const fallback=()=>node('span',abbr,'src-abbr');if(icon){const img=document.createElement('img');img.src=icon;img.alt='';img.width=img.height=16;img.className='src-icon';img.onerror=()=>img.replaceWith(fallback());wrap.append(img)}else wrap.append(fallback());wrap.append(node('span',name,'src-name'));return wrap}
function error(e){$('error').hidden=false;$('error').textContent=e.message||String(e)}
async function api(path,options={}){const headers={'Content-Type':'application/json'};if(token)headers.Authorization=`Bearer ${token}`;let r;try{r=await fetch(path,{...options,headers})}catch{throw Error('Không kết nối được máy chủ')}let b={};try{b=await r.json()}catch{if(r.ok)throw Error('Máy chủ trả dữ liệu không hợp lệ')}if(!r.ok){if(r.status===401){authRequired=true;lock()}throw Error(b.error||`Máy chủ trả lỗi HTTP ${r.status}`)}return b}
function lock(){token='';try{session&&session.removeItem('news-token')}catch{}$('workspace').hidden=true;$('booting').hidden=true;$('login').hidden=false;$('logout').hidden=true;$('token').value=''}
function show(v){if(v!=='reader')videos.stopAll();view=v;$('error').hidden=true;$('news-view').hidden=v!=='news';$('sources-view').hidden=v!=='sources';$('reader').hidden=v!=='reader';$('news-tab').classList.toggle('active',v==='news');$('sources-tab').classList.toggle('active',v==='sources')}

// Categories and "new since you last opened it" badges.
async function loadCategories(){const res=await api(`/api/categories?seen=${encodeURIComponent(seen.param())}`);categories=res.categories;seen.sync(categories.map(c=>c.slug),res.cursor);renderCategories()}
function renderCategories(){const bar=$('categories');bar.replaceChildren();const all=node('button',undefined,'cat');all.append(node('span','Tất cả'));all.setAttribute('aria-pressed',String(category===''));all.onclick=()=>selectCategory('');bar.append(all);for(const c of categories){const b=node('button',undefined,'cat');b.append(node('span',c.name));if(c.new_count>0)b.append(newDot('Có bài mới'));b.setAttribute('aria-pressed',String(category===c.slug));b.onclick=()=>selectCategory(c.slug);bar.append(b)}const active=bar.querySelector('[aria-pressed="true"]');if(active&&active.scrollIntoView)active.scrollIntoView({block:'nearest',inline:'nearest'})}
function fillCategorySelect(sel,value){sel.replaceChildren();for(const c of categories)sel.add(new Option(c.name,c.slug));sel.value=value}
function selectCategory(slug){category=slug;page=1;$('news-title').textContent=slug?catName(slug):'Tin mới';renderCategories();loadArticles({userAction:true}).catch(error)}

async function loadEnrichStatus(){try{const st=(await api('/api/status')).enrich;$('enrich-status').hidden=false;$('enrich-status').textContent=`Bổ sung tác giả, ảnh và video cho bài đã lưu: ${st.done} bài xong, ${st.pending} bài đang chờ (lấy dần, tối đa 6 bài/nguồn/lượt)${st.failed?`, ${st.failed} bài không lấy được (giữ nội dung cũ)`:''}.`}catch{$('enrich-status').hidden=true}}
async function loadSources(){loadEnrichStatus();sources=await api('/api/sources');const chosen=$('source-filter').value;$('source-filter').replaceChildren(new Option('Tất cả nguồn',''));for(const s of sources)$('source-filter').add(new Option(s.name,String(s.id)));$('source-filter').value=sources.some(s=>String(s.id)===chosen)?chosen:'';renderSources()}
function renderSources(){$('sources').replaceChildren();for(const s of sources){const card=node('div',undefined,'source-card');const title=node('h2');title.append(sourceLabel(s.adapter,s.name));const rename=node('form',undefined,'rename');const nameLabel=node('label','Tên hiển thị','inline');const nameIn=node('input');nameIn.value=s.name;nameIn.maxLength=100;nameIn.required=true;nameLabel.append(nameIn);const save=node('button','Lưu tên');rename.append(nameLabel,save);rename.onsubmit=async e=>{e.preventDefault();const v=nameIn.value.trim();if(!v||v===s.name){nameIn.value=s.name;return}save.disabled=true;try{await api(`/api/sources/${s.id}`,{method:'PATCH',body:JSON.stringify({name:v})});await loadSources();loadArticles().catch(()=>{})}catch(e){error(e);nameIn.value=s.name}finally{save.disabled=false}};card.append(title,node('p',s.feed_url),node('p',s.enabled?'Đang lấy tin':'Đã tắt'),node('p',`Kiểm tra gần nhất: ${fmt(s.last_checked)} · Thành công: ${fmt(s.last_success)}`));if(s.last_error)card.append(node('p',s.last_error,'error'));const actions=node('div',undefined,'actions');const label=node('label','Chuyên mục','inline');const sel=node('select');fillCategorySelect(sel,s.category);sel.onchange=async()=>{sel.disabled=true;try{await api(`/api/sources/${s.id}`,{method:'PATCH',body:JSON.stringify({category:sel.value})});await loadSources();await loadCategories()}catch(e){error(e);sel.value=s.category}finally{sel.disabled=false}};label.append(sel);const toggle=node('button',s.enabled?'Tắt nguồn':'Bật nguồn');toggle.onclick=async()=>{toggle.disabled=true;try{await api(`/api/sources/${s.id}`,{method:'PATCH',body:JSON.stringify({enabled:!s.enabled})});await loadSources()}catch(e){error(e)}finally{toggle.disabled=false}};const remove=node('button','Xoá nguồn');remove.onclick=async()=>{if(!confirm(`Xoá ${s.name}? Các bài nguồn này lấy về sẽ được ẩn.`))return;try{await api(`/api/sources/${s.id}`,{method:'DELETE'});await loadSources();await Promise.all([loadCategories(),loadArticles()])}catch(e){error(e)}};actions.append(label,toggle,remove);card.append(rename,actions);$('sources').append(card)}}

// userAction: the user opened or changed this list. Only then may a category
// be marked seen, and only after the request succeeded (see seen.js).
async function loadArticles({userAction=false}={}){const fresh=latestList.next();const opts={userAction,query:search.applied,source:$('source-filter').value};const params=new URLSearchParams({page,source:opts.source,q:opts.query,category});const before=seen.snapshot();$('list-status').textContent='Đang tải tin…';$('articles').setAttribute('aria-busy','true');$('prev').disabled=$('next').disabled=true;try{const res=await SeenStore.loadAndMark(seen,()=>api(`/api/articles?${params}`),category,opts);if(!fresh())return;renderArticles(res,before)}catch(e){if(fresh()){$('list-status').textContent='Không tải được danh sách tin. Bấm “Tải lại” để thử lại.';$('prev').disabled=page===1}throw e}finally{if(fresh())$('articles').removeAttribute('aria-busy')}if(userAction&&category)loadCategories().catch(()=>{})}
function renderArticles(res,before){const items=res.items;$('articles').replaceChildren();for(const a of items){const card=node('article',undefined,'card');const meta=node('div',undefined,'meta');meta.append(sourceLabel(a.adapter,a.source),node('span',(a.categories||[]).map(catName).join(', ')),node('span',fmt(a.published_at)));const badges=node('div',undefined,'badges');if(a.has_video)badges.append(node('span','Video','badge video-badge'));badges.append(node('span',statusText[a.content_status]||'Bản tóm tắt','badge'));const h=node('h2',a.title);if(SeenStore.isNew(a,before))h.append(newDot('Bài mới'));card.append(meta,h,badges,node('p',a.summary));const read=node('button','Đọc bài');read.onclick=()=>openArticle(a.id);card.append(read);$('articles').append(card)}const filtered=search.applied||$('source-filter').value;$('list-status').textContent=items.length?`${items.length} bài trên trang này`:(page>1?'Không còn bài ở trang này.':filtered?'Không có bài phù hợp bộ lọc.':category?'Chuyên mục này chưa có bài. Chuyên mục chỉ nhận bài từ các feed được gán vào nó (xem Nguồn tin).':'Chưa có tin. Nguồn mới sẽ được kiểm tra ở lượt lấy tin tiếp theo; xem trạng thái trong Nguồn tin.');$('page-label').textContent=`Trang ${page}`;$('prev').disabled=page===1;$('next').disabled=!res.has_more}
// Images come straight from the source CDNs allowed by the CSP; the server
// already validated the URLs, this check only keeps the DOM consistent.
const posterOK=src=>{try{const u=new URL(src);return u.protocol==='https:'&&imageHost(u.hostname)}catch{return false}};
const imageHost=h=>h==='ichef.bbci.co.uk'||h.endsWith('.vnecdn.net')||h==='cdn2.tuoitre.vn';
function imageFigure(im,eager){let u;try{u=new URL(im.src)}catch{return null}if(u.protocol!=='https:'||!imageHost(u.hostname))return null;const fig=node('figure',undefined,'media');const img=document.createElement('img');img.alt=im.alt||'';if(im.width&&im.height){img.width=im.width;img.height=im.height}img.loading=eager?'eager':'lazy';img.decoding='async';img.referrerPolicy='no-referrer';if(im.srcset){img.srcset=im.srcset;img.sizes='(max-width: 800px) calc(100vw - 2rem), 760px'}img.onerror=()=>{img.remove();fig.classList.add('failed');fig.prepend(node('div','Không tải được ảnh từ nguồn.','img-error'))};img.src=u.href;fig.append(img);if(im.caption||im.credit){const fc=node('figcaption');if(im.caption)fc.append(node('span',im.caption,'caption'));if(im.credit)fc.append(node('span',`Ảnh: ${im.credit}`,'credit'));fig.append(fc)}return fig}
async function openArticle(id){videos.stopAll();$('list-status').textContent='Đang mở bài…';try{const a=await api(`/api/articles/${id}`);$('list-status').textContent='';const cats=(a.categories||[]).map(catName).join(', ');$('reader-meta').replaceChildren(node('span','Nguồn:'),sourceLabel(a.adapter,a.source),node('span',`${cats?'· '+cats+' ':''}· ${fmt(a.published_at)}`));$('reader-title').textContent=a.title;const authors=a.authors||[];$('reader-authors').hidden=!authors.length;$('reader-authors').textContent=authors.length?`Tác giả: ${authors.join(', ')}`:'';$('reader-summary').textContent=a.summary;const full=a.content_status==='full';$('reader-status').hidden=full;$('reader-status').textContent=a.content_status==='summary'?'Đây là bản tóm tắt từ RSS. Nội dung đầy đủ đang chờ được lấy; đọc toàn bài tại nguồn gốc.':'Đây là bản tóm tắt từ RSS. Không lấy được toàn văn (bài video, tương tác, trang bị gỡ hoặc cấu trúc trang thay đổi); đọc toàn bài tại nguồn gốc.';$('reader-enrich').hidden=!(full&&!a.enriched);// Without full text only the page's videos are shown (never partial text).
const blocks=(a.blocks||[]).filter(b=>full||b.type==='video');let firstP=true,imgs=0;$('reader-lead').replaceChildren();$('reader-body').replaceChildren();if(a.lead_image&&!blocks.some(b=>b.type==='img'||b.type==='video')){const f=imageFigure(a.lead_image,true);if(f)$('reader-lead').append(f)}for(const b of blocks){if(b.type==='p'){if(firstP&&b.text.trim()===a.summary.trim()){firstP=false;continue}firstP=false;$('reader-body').append(node('p',b.text))}else if(b.type==='img'&&b.image){const f=imageFigure(b.image,imgs===0);imgs++;if(f)$('reader-body').append(f)}else if(b.type==='video'&&b.video){$('reader-body').append(videos.figure(b.video,{articleTitle:a.title,sourceName:a.source,posterOK:posterOK}))}}const url=new URL(a.url);if(url.protocol!=='https:')throw Error('Liên kết bài không hợp lệ');$('original').href=url.href;$('original').textContent=`Đọc bài gốc tại ${a.source}`;show('reader');window.scrollTo({top:0,behavior:'smooth'})}catch(e){$('list-status').textContent='';error(e)}}

async function start(){try{$('error').hidden=true;await loadCategories();await loadSources();await loadArticles();if(token&&session)session.setItem('news-token',token);$('booting').hidden=true;$('login').hidden=true;$('workspace').hidden=false;$('logout').hidden=!authRequired;show('news')}catch(e){$('booting').hidden=true;if(!authRequired&&$('workspace').hidden){$('workspace').hidden=false;show('news')}error(e)}}
async function boot(){try{const r=await fetch('/api/session',{cache:'no-store'});authRequired=(await r.json()).auth_required!==false}catch{authRequired=true}if(!authRequired||token)start();else lock()}
$('login-form').onsubmit=e=>{e.preventDefault();token=$('token').value;start()};$('logout').onclick=lock;
$('news-tab').onclick=()=>{if(!$('workspace').hidden)show('news')};$('sources-tab').onclick=()=>{if(!$('workspace').hidden){show('sources');loadSources().catch(error)}};$('back').onclick=()=>show('news');
$('filters').onsubmit=e=>{e.preventDefault();search.submit($('query').value)};
for(const ev of ['input','search'])$('query').addEventListener(ev,()=>search.changed($('query').value));$('source-filter').onchange=()=>{page=1;loadArticles({userAction:true}).catch(error)};
$('reload').onclick=()=>Promise.all([loadCategories(),loadSources(),loadArticles({userAction:true})]).catch(error);
$('prev').onclick=()=>{if(page>1){page--;loadArticles({userAction:true}).catch(error)}};$('next').onclick=()=>{page++;loadArticles({userAction:true}).catch(error)};
// Adding a source (the only add flow): the server recognises the URL, checks
// each feed and stores it; the result is rendered as text only. Failures
// offer a mailto with only the typed URL.
let importing=false;
function renderImport(o,input){const box=$('import-result');box.replaceChildren();box.hidden=false;box.className='import-result '+o.tone;box.setAttribute('role',o.tone==='ok'?'status':'alert');box.append(node('p',o.text,'import-msg'));if(o.details&&o.details.length){const det=node('details');det.append(node('summary','Chi tiết'));const ul=node('ul');for(const d of o.details)ul.append(node('li',d));det.append(ul);box.append(det)}if(o.report){const act=node('div',undefined,'import-report');const mail=node('a','Báo lỗi qua email','button-link');mail.href=Importer.reportHref(input);const copy=node('button','Sao chép URL');copy.type='button';copy.onclick=async()=>{try{await navigator.clipboard.writeText(input);copy.textContent='Đã sao chép'}catch{$('import-url').select();copy.textContent='Hãy nhấn Ctrl/Cmd+C'}};const addr=node('span',`Không mở được ứng dụng email? Gửi URL tới ${Importer.REPORT_TO} (tiêu đề “${Importer.REPORT_SUBJECT}”).`,'muted small');act.append(mail,copy,addr);box.append(act)}}
$('import-source').onsubmit=async e=>{e.preventDefault();if(importing)return;const input=$('import-url').value.trim();if(!input){renderImport({tone:'error',report:false,text:'Hãy dán URL website hoặc RSS.'},input);return}importing=true;const btn=$('import-btn');btn.disabled=true;$('import-url').readOnly=true;btn.textContent='Đang thêm…';const box=$('import-result');box.hidden=false;box.className='import-result busy';box.setAttribute('role','status');box.replaceChildren(node('p','Đang kiểm tra nguồn…','import-msg'));let status=0,body=null;try{const headers={'Content-Type':'application/json'};if(token)headers.Authorization=`Bearer ${token}`;const r=await fetch('/api/sources/import',{method:'POST',headers,body:JSON.stringify({url:input})});status=r.status;try{body=await r.json()}catch{body=null}}catch{status=0}finally{importing=false;btn.disabled=false;$('import-url').readOnly=false;btn.textContent='Thêm nguồn'}if(status===0){renderImport({tone:'error',report:false,text:'Không kết nối được máy chủ. Kiểm tra app đang chạy rồi thử lại.'},input);return}const o=Importer.outcome(status,body);renderImport(o,input);if(status===401){authRequired=true;lock();return}if(body&&((body.added||[]).length||(body.restored||[]).length||(body.existing||[]).some(f=>f.note))){await loadSources().catch(error);loadCategories().catch(()=>{})}if(body&&body.status==='ok')$('import-url').value=''};
// Background refresh: updates counts and the list, never marks anything seen.
setInterval(()=>{if(!$('workspace').hidden&&view==='news')Promise.all([loadCategories(),loadArticles()]).catch(()=>{$('list-status').textContent='Không cập nhật được; sẽ thử lại sau.'})},120000);
boot();
